# MAIN base
baseURL = "https://venture365.co/"
languageCode = "en-us"
title = "Venture365"
theme = "hugo-apsho-master"

# Navigation Bar
[[menu.main]]
    name = "Home"
    url = "#hero"
    weight = 1

[[menu.main]]
    name = "Interviews"
    url = "#interviews"
    weight = 2

[[menu.main]]
    name = "Articles"
    url = "#articles"
    weight = 3

[[menu.main]]
    name = "Projects"
    url = "#projects"
    weight = 3

# Footer Sitemap

[[menu.sitemap]]
    name = "Imprint"
    url = "/imprint"
    weight = 2

[[menu.sitemap]]
    name = "Privacy & Policy"
    url = "/privacy"
    weight = 1

[[menu.sitemap]]
    name = "Contact"
    url = "/contact"
    weight = 3

[[menu.mainfooter]]
    name = "Home"
    url = "/home"
    weight = 1

[[menu.mainfooter]]
    name = "Interviews"
    url = "/interviews"
    weight = 2

[[menu.mainfooter]]
    name = "Articles"
    url = "/articles"
    weight = 3


[[menu.mainfooter]]
    name = "Projects"
    url = "/projects"
    weight = 4

# Footer Address
[params.address]
address = "Hietzinger Hauptstraße, 1080 Vienna"
email = "team@venture365.org"
phone = "+43 660 000 0000"

# Footer Social
[params.social]
facebook = "https://www.facebook.com"
twitter = "https://twitter.com/"
github = "https://github.com"

[params]

# Header
logo = "images/logo4.png"
fabFormURL = "https://fabform.io/f/zWMBVeW"
googleAnalytics = "UA-175025671-2"

# Footer
footerTitle = "Join Our Newsletter"
copyright1 = "All right reserved"
copyright2 = "Copyright © Venture365 {year}"

#contact
email = "help@staticmania.com"
 