# MAIN base
baseURL = "https://venture365.co/"
languageCode = "en-us"
title = "Venture365"
theme = "hugo-apsho-master"

# Navigation Bar
[[menu.main]]
    name = "Home"
    url = "#hero"
    weight = 1
[[menu.main]]
    name = "About"
    url = "#services"
    weight = 2

[[menu.main]]
    name = "Blog"
    url = "#blog"
    weight = 3

# Footer Sitemap
[[menu.sitemap]]
    name = "Home"
    url = "#"
    weight = 1

[[menu.sitemap]]
    name = "Latest Article"
    url = "/blog"
    weight = 2
[[menu.sitemap]]
    name = "Privacy & Policy"
    url = "/privacy"
    weight = 3
[[menu.sitemap]]
    name = "Contact"
    url = "/contact"
    weight = 4

# Footer Address
[params.address]
address = "Hietzinger Hauptstraße, 1080 Vienna"
email = "team@venture365.org"
phone = "+43 660 000 0000"

# Footer Social
[params.social]
facebook = "https://www.facebook.com"
twitter = "https://twitter.com/"
github = "https://github.com"

[params]

# Header
logo = "images/logo4.png"
fabFormURL = "https://fabform.io/f/zWMBVeW"
googleAnalytics = "UA-175025671-2"

# Footer
footerTitle = "Join our newsletter"
copyright1 = "All right reserved"
copyright2 = "Copyright © Venture365 {year}"

#contact
email = "help@staticmania.com"
 